language: node_js
node_js:
  - 12
sudo: required
services:
  - docker

before_install:
  - docker build -t ericsoucy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ericsoucy/docker-react npm run test

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-779702986911"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
