version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - //dev/docker-and-kubernetes-the-complete-guide/section6/frontend:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - //dev/docker-and-kubernetes-the-complete-guide/section6/frontend:/app
    command: ["npm", "test"]
